### ISSUE TITLE
statische Kennlinie

### ISSUE THREAD

**Issue by DonkeyCo** [Ralerus/Signale-Systeme#10]
- [x] Definieren
- [x] Visualisieren
- dcgain liefert infinite
- [ ] Text überprüfen

dcgain(sys) liefert statische Verstärkung
Gerade zeichnen, Achsen beschriften, Titel setzen

**Comment by Ralerus** [comment]
statische Verstärkung ist unendlich, anpassen
G(0) -> oo

**Comment by Ralerus** [comment]
guck mal noch drüber @DonkeyCo
