### ISSUE TITLE
explizite Lösung

### ISSUE THREAD

**Issue by DonkeyCo** [Ralerus/Signale-Systeme#3]
- [ ] Definieren
- [ ] Visualisieren

**Comment by Ralerus** [comment]
Exponentialmatrix ergänzen, nachdem Zustandsraum und damit Systemmatrix überprüft wurde. 
Lösungen für x1, x2, ... rausschreiben

**Comment by Ralerus** [comment]
Integral zur vollständigkeit nicht vergessen, Exponentialmatrix nur homogene Lösung, Rest fehlt theoretisch noch
